package com.lukai.crm.settings.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.lukai.crm.settings.domain.User;
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Oct 20 09:07:55 JST 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Oct 20 09:07:55 JST 2025
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Oct 20 09:07:55 JST 2025
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Oct 20 09:07:55 JST 2025
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Oct 20 09:07:55 JST 2025
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Mon Oct 20 09:07:55 JST 2025
     */
    int updateByPrimaryKey(User row);
    
    /*
     * アカウントとパスワードを元に、ユーザーが存在するかどうかを検索します。
     * */
    User selectUserByloginAct(String loginAct);
    
    List<User> queryAllUsers();
    
    int updatePwd(User user);
}